### ISSUE TITLE
How does the VAST-2-SGAI proxy knows who is asking for the Interstitial content?

### ISSUE THREAD

**Issue by nicolaslevy** [montevideo-tech/vast-2-sgai#2]
How the VAST-2-SGAI proxy knows who is asking for the Interstitial content? We need to Understand HLS Interstitial Query Parameters.

When HLS players make a request to obtain a response for Interstitials (either via **X-ASSET-List** or **X-ASSET-URI**), the player sends specific query parameters.  
We need to understand which parameters are being sent and what has been implemented in **hls.js** version 1.6 beta, as this will be necessary for requesting the **VAST/VAMP** from the Ad server.

![image](https://github.com/user-attachments/assets/ddc7456c-04c5-455e-8603-b0a28fac35ba)

**Comment by nicolaslevy** [comment]
Its Interstitial query parameters are defined in https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis-16#appendix-D.3




| **Query Parameter / Header**       | **Requirement**         | **Description**                                                                                           | **Notes/Rules**                                                                                         |
|------------------------------------|-------------------------|-----------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------|
| `_HLS_interstitial_id`             | **Required** (Recommended) | Contains the quoted `ID` attribute value of the `EXT-X-DATERANGE` tag.                                    | Supports interoperability between content producers and decisioning servers.                            |
| `_HLS_primary_id`                  | Optional (Recommended)  | Matches the `X-PLAYBACK-SESSION-ID` header value of the primary playback session.                         | - If clients cannot set the header, they must generate a globally-unique value for `_HLS_primary_id`.<br> - Should be added to interstitial and primary asset requests. |
| `_HLS_start_offset`                | Optional                | Contains the offset in seconds of the playback start point from the beginning of the interstitial.        | Only for `X-ASSET-LIST` requests when starting playback of a live stream in an interstitial.            |

| **Rule**                            | **Details**                                                                                             |
|-------------------------------------|---------------------------------------------------------------------------------------------------------|
| **Unique Session Identification**   | Clients must generate a globally-unique value for `_HLS_primary_id` if unable to set `X-PLAYBACK-SESSION-ID`. |
| **Consistent Usage**                | `_HLS_primary_id` must be included in all requests related to the playback session, including interstitials. |
| **Start Offset Customization**      | `_HLS_start_offset` must be included in `X-ASSET-LIST` requests when starting playback in an interstitial of a live stream. |
| **Request Types**                   | Query parameters apply to: <br>- `X-ASSET-URI` requests<br>- `X-ASSET-LIST` requests<br>- Requests for URIs in an `X-ASSET-LIST` JSON Asset Description.|

About the X-PLAYBACK-SESSION-ID: https://github.com/video-dev/hls.js/issues/5770#issuecomment-1694400340

> Apple players add a X-PLAYBACK-SESSION-ID header with every http request which contains the same uuid for the asset/player session. HLS.js does not, and is not required to...


From this:
* From the previous table, we should understand what is supported in hls.js 1.6  beta
* (Optional) Also would be interesting to understand what is supported in iOS and Safari

**Comment by jaram-qualabs** [comment]
# hls.js 
In the process of understanding the Interstitial query parameters, we wanted to understand how `hls.js` player handled the previously mentioned params. 

## _HLS_primary_id
This param is added automatically by the player, and the value is set to the `sessionId` before making the request.

Code:
https://github.com/video-dev/hls.js/blob/7db2f5263ef707b3c9e4ec5dc9a0df56e03fe922/src/loader/interstitial-event.ts#L274-L283

## _HLS_interstitial_id
There are no references in the code, the player does not add the ID automatically.
In the tests, we can see that is added directly into the interstitial uri, however, I'm not sure if that would be a real-life case scenario.

Code:
https://github.com/video-dev/hls.js/blob/7db2f5263ef707b3c9e4ec5dc9a0df56e03fe922/tests/unit/loader/playlist-loader.ts#L1801-L1832

## _HLS_start_offset
Based on the code, it should be automatically added for live streams with interstitials asset list. It's still to be manually tested.

Code:
https://github.com/video-dev/hls.js/blob/7db2f5263ef707b3c9e4ec5dc9a0df56e03fe922/src/loader/interstitial-asset-list.ts#L32C2-L66C6

**Comment by nicolaslevy** [comment]
About: _HLS_interstitial_id
So basicaly we can build the ASSET List URI taking that into account. 

Example form the link you sent @jaram-qualabs :
> EXT-X-DATERANGE:ID="mid2",CLASS="com.apple.hls.interstitial",START-DATE="2024-01-12T10:00:25.000Z",DURATION=15.0,X-ASSET-URI="b.m3u8?_HLS_interstitial_id=mid2",X-SNAP="OUT,IN"

**Comment by fcancela** [comment]
### Proposal: Replace Existing Interstitial Query Parameter Handling with `#EXT-X-DEFINE:QUERYPARAM` from HLS Spec

Building on the previous discussion about handling interstitials with `_HLS_interstitial_id` and `_HLS_primary_id` as part of the standard, I propose using the `#EXT-X-DEFINE:QUERYPARAM` functionality defined in the [RFC8216bis spec, Section 4.4.2.3](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.2.3) as an alternative. While those parameters are valid and part of the standard, this approach is simpler and more practical for dynamic query parameter handling. 

I’ve tested this implementation, and it works.

---

### Why Use `#EXT-X-DEFINE:QUERYPARAM`?

- **Simpler Implementation**: Unlike `_HLS_interstitial_id` and `_HLS_primary_id`, this approach handles query parameters dynamically with minimal configuration and complexity.
- **Standards-Based**: Fully compliant with the HLS spec, ensuring compatibility and interoperability with players.
- **Improved CDN Cacheability**: The manifest remains static, with query parameters enabling personalization without affecting cache efficiency.

---

### Working Example

#### HTML Setup (HLS.js Canary)

```html
<video id="video" controls width="640" height="360"></video>
<script src="https://cdn.jsdelivr.net/npm/hls.js@1.6.0-beta.1.0.canary.10748"></script>
<script>
  if (Hls.isSupported()) {
    const hls = new Hls();
    const token = "user-session-token"; // Replace with dynamic token logic
    hls.loadSource(`./playlist.m3u8?token=${token}`);
    hls.attachMedia(document.getElementById("video"));
  }
</script>
```

#### HLS Playlist

```m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:11
#EXT-X-DEFINE:QUERYPARAM="token"
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:10.000000,
segment1.ts?{$token}
#EXTINF:11.200000,
segment2.ts?{$token}
#EXT-X-ENDLIST
#EXT-X-DATERANGE:ID="ad1",CLASS="com.apple.hls.interstitial",
START-DATE="2024-01-12T10:00:25.000Z",DURATION=15.0,
X-ASSET-URI="https://example.com/ad.m3u8?{$token}",
X-SNAP="OUT,IN"
```

---

### Key Changes

1. **Leverages `#EXT-X-DEFINE:QUERYPARAM`**:
   - The `#EXT-X-DEFINE:QUERYPARAM="token"` tag dynamically substitutes `{$token}` placeholders with the value in the playlist URL’s query string.
   - Applies consistently to both primary content (`segment1.ts`) and interstitials (`X-ASSET-URI`, `X-ASSET-LIST`).

2. **Dynamic Personalization**:
   - Personalization is handled via a `token` query parameter appended dynamically at runtime.

3. **CDN-Friendly**:
   - Manifests remain static, allowing efficient CDN caching while maintaining user-specific personalization.

---

### Next Steps for Discussion
1. Does updating server logic to dynamically append the `token` query parameter fit our current solution?  

Let me know your thoughts or if more examples/tests are needed!

**Comment by nicolaslevy** [comment]
Thanks @fcancela. I updated the samples in the repo. It works perfect with hls.js 1.6 beta.

![image](https://github.com/user-attachments/assets/33886415-9285-45af-9ac3-e3f8f475e988)

**Comment by nicolaslevy** [comment]
I think we are done with this ticket. Now that we understand how to use QUERYPARAMS, we have everything we need to bypass any setting, user_id, or parameter we need
